db connectivity
realwebdev/clockify_backend_clone pull request #1
Opened 2021-07-20 09:17 UTC by realwebdev

gorm structs

2021-07-20 09:44 UTC, Bilaltanveer38 requested changes

2021-07-20 09:44 UTC, Bilaltanveer38 commented on .env
> +PASSWORD="password"
.env file should not be included in the git repo, must add .gitignore file

2021-07-20 09:44 UTC, Bilaltanveer38 commented on main.go
> +
There should be a package named models, and each struct have its own file.

2021-07-20 09:44 UTC, Bilaltanveer38 commented on main.go
> +
There should be a seperate package conf with conf.go file, and all the handling of environment variables should be done there.

2021-07-20 09:44 UTC, Bilaltanveer38 commented on main.go
> +
Write a function CreateUser(username, email, password string) instead of making a variable

2021-07-20 09:44 UTC, Bilaltanveer38 commented on main.go
> +
We should never create the global variables

2021-07-20 09:44 UTC, Bilaltanveer38 commented on main.go
> +	db.Create(user)
This should have handled in CreateUser function

2021-07-20 09:44 UTC, Bilaltanveer38 commented on main.go
> +
There should be a package named Datastore or DB, and all of the db based operations like establishing connection returning DB object, should be done there.

2021-07-20 09:44 UTC, Bilaltanveer38 commented on main.go
> +	db.Create(user)
Moreover, the project is not 'gofmt', make sure to gofmt the project before pushing it on the repo.

2021-07-27 11:59 UTC, zunnorainzaheer commented on database/conn.go
> +
Should load the env file in the separate package named conf

2021-07-27 11:59 UTC, Bilaltanveer38 commented on database/conn.go
> +
Should load the env file in the separate package named conf

2021-07-27 12:00 UTC, Bilaltanveer38 commented on database/conn.go
> +	var errr error
use err instead errr

2021-07-27 12:01 UTC, Bilaltanveer38 commented on database/conn.go
> +	db, errr = gorm.Open(dialect, dbURI)
or use this db,err:= gorm.Open(dialect, dbURI) 
this syntax is recommended

2021-07-27 12:04 UTC, Bilaltanveer38 commented on database/conn.go
> +
return db

2021-07-27 12:04 UTC, Bilaltanveer38 commented on database/conn.go
> +		fmt.Println("Connected to database successfully")
remove else block

2021-07-27 12:08 UTC, Bilaltanveer38 commented on database/conn.go
> +	// Loading enviroment variables
no need to create the object

2021-07-27 12:09 UTC, Bilaltanveer38 commented on database/conn.go
> +
create a wrapper function instead of calling this

2022-08-16 16:08 UTC, merged